# -*- coding: utf-8 -*-
"""project.3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aNGROKKmqHBi_U1LzIJf7X9etWmvK2c7
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import numpy as np

# --------------------------------------------------
# Page Configuration
# --------------------------------------------------
st.set_page_config(
    page_title="Canada Per Capita Income Prediction",
    page_icon="📈",
    layout="wide"
)

# --------------------------------------------------
# Title
# --------------------------------------------------
st.title("📈 Canada Per Capita Income Prediction")
st.markdown(
    """
This app uses **Linear Regression** to predict the **Per Capita Income (US$)** of Canada
based on historical data.
"""
)

# --------------------------------------------------
# Load Dataset
# --------------------------------------------------
df = pd.read_csv("canada_per_capita_income.csv")

# Display Dataset
st.subheader("📊 Dataset")
st.dataframe(df, use_container_width=True)

# --------------------------------------------------
# Train Model
# --------------------------------------------------
X = df[['year']]
y = df['per capita income (US$)']

model = LinearRegression()
model.fit(X, y)

# --------------------------------------------------
# Model Information
# --------------------------------------------------
st.subheader("📌 Model Information")

col1, col2 = st.columns(2)

with col1:
    st.metric("Slope", f"{model.coef_[0]:.2f}")

with col2:
    st.metric("Intercept", f"{model.intercept_:.2f}")

# --------------------------------------------------
# Prediction
# --------------------------------------------------
st.subheader("🔮 Predict Income")

year = st.number_input(
    "Enter Year",
    min_value=1960,
    max_value=2050,
    value=2020,
    step=1
)

prediction = model.predict([[year]])

st.success(
    f"Estimated Per Capita Income in **{year}** is **${prediction[0]:,.2f}**"
)

# --------------------------------------------------
# Regression Graph
# --------------------------------------------------
st.subheader("📉 Regression Plot")

fig, ax = plt.subplots(figsize=(10,5))

ax.scatter(
    df['year'],
    df['per capita income (US$)'],
    color="blue",
    label="Actual Data"
)

ax.plot(
    df['year'],
    model.predict(df[['year']]),
    color="red",
    linewidth=3,
    label="Regression Line"
)

ax.set_xlabel("Year")
ax.set_ylabel("Per Capita Income (US$)")
ax.set_title("Canada Per Capita Income")
ax.legend()

st.pyplot(fig)

# --------------------------------------------------
# Predict Future Years
# --------------------------------------------------
st.subheader("📈 Future Predictions")

future_years = np.arange(year, year+11).reshape(-1,1)
future_income = model.predict(future_years)

future_df = pd.DataFrame({
    "Year": future_years.flatten(),
    "Predicted Income (US$)": future_income
})

st.dataframe(future_df, use_container_width=True)

# --------------------------------------------------
# Footer
# --------------------------------------------------

st.markdown("---")

st.markdown(
"""
<div style="padding:20px;border-radius:12px;background-color:#0E1117;border:1px solid #444;text-align:center;">

<h2>👨‍💻 Richeek Pandey</h2>

<h4>📊 Data Science | Machine Learning | Python Developer</h4>

<p>
This application was built using <b>Python</b>, <b>Scikit-learn</b>,
<b>Pandas</b>, <b>Matplotlib</b> and <b>Streamlit</b>.
</p>

<p>
🔗 <a href="https://www.linkedin.com/in/richeek-pandey-9954783a9" target="_blank">LinkedIn</a> |
💻 <a href="https://github.com/richeekpandey07" target="_blank">GitHub</a>
</p>

<p>⭐ Thanks for exploring my project!</p>

</div>
""",
unsafe_allow_html=True
)
